# Generated by Django 5.1.4 on 2025-01-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_employee_birth_date_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_handle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='access_level',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Guest', 'Guest')], default='Employee', max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
