# Generated by Django 5.1.4 on 2025-01-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0003_alter_education_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='course_of_study',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
