# Generated by Django 5.1.6 on 2025-02-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0006_rename_year_graduated_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course_of_study',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ManyToManyField(blank=True, to='employee_management.team'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(blank=True, to='employee_management.permission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='team',
            field=models.ManyToManyField(blank=True, to='employee_management.team'),
        ),
    ]
