# Generated by Django 5.1.6 on 2025-02-16 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0008_alter_permission_name_alter_role_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surbodinates', to='employee_management.role'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(),
        ),
    ]
