# Generated by Django 5.1.6 on 2025-02-24 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0009_alter_permission_description_alter_role_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='employee_management.employee'),
        ),
    ]
