# Generated by Django 5.1.6 on 2025-02-25 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0010_alter_education_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='employee_management.employee'),
        ),
    ]
