# Generated by Django 5.1.6 on 2025-02-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0012_remove_address_id_alter_address_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(editable=False, max_length=14, primary_key=True, serialize=False, unique=True),
        ),
    ]
