# Generated by Django 5.1.6 on 2025-02-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0013_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='employement',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('associate', 'Associate')], default='full_time', max_length=20),
        ),
    ]
