# Generated by Django 5.1.6 on 2025-02-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0014_role_employement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='employement',
            new_name='employement_type',
        ),
    ]
