# Generated by Django 5.1.6 on 2025-02-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0017_alter_employee_options_remove_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='employment_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Associate', 'Associate')], default='Full-time', max_length=20),
        ),
    ]
