# Generated by Django 5.1.6 on 2025-02-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0020_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
