# Generated by Django 5.1.6 on 2025-03-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0021_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True),
        ),
    ]
