# Generated by Django 5.1.7 on 2025-03-16 21:36

import django.db.models.deletion
import employee_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0025_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeImage',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='image', serialize=False, to='employee_management.employee')),
                ('image', models.ImageField(upload_to='employee_management/images', validators=[employee_management.validators.validate_file_size])),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
