# Generated by Django 5.1.7 on 2025-03-21 05:10

import django.utils.timezone
import employee_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0027_alter_employeeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeeimage',
            name='image',
            field=models.ImageField(upload_to='employee_management/images', validators=[employee_management.validators.validate_file_size]),
        ),
    ]
