services:
  - type: web
    name: aerten-web
    env: python
    buildCommand: pip install -r aerten-web/requirements.txt
    startCommand: |
      cd aerten-web
      python manage.py collectstatic --noinput
      python manage.py migrate
      gunicorn aerten.wsgi:application --bind=0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DJANGO_LOG_LEVEL
        value: INFO
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DATABASE_URL
        fromDatabase:
          name: aerten_db
          property: connectionString
      - key: PORT
        value: 8000
    staticPublishPath: ./static
    autoDeploy: true

  - type: postgresql
    name: aerten_db
    plan: free
    ipAllowList: []
